### ISSUE TITLE
Export an es2018/esnext build

### ISSUE THREAD

**Issue by NotWoods** [getinsights/insights-js#1]
Some of my apps target newer browsers and I'd like to ship less code, using features like classes. I'd like a file in the `dist/` folder that is in JS but keeps the modern ES2015+ syntax.

**Comment by Mytrill** [comment]
Hi, 
I just added the esnext build in https://github.com/getinsights/insights-js/commit/38981b910e4247268c919943ac1c3a01213d23d0 and published version 1.2.10 to npm.

The entry is in `dist/esnext/index.js`.

Let me know if there are any issues with this.
